version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT:-8081}
    container_name: myapp-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT:-8081}
    networks:
      - myapp-network

    healthcheck:
      test: ["CMD", "/app", "--health-check"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

    # security
    read_only: true
    tmpfs: /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=/api
    container_name: myapp-frontend
    ports:
      - "3000:80"
    networks:
      - myapp-network
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8081}
      - FRONTEND_PORT=3000
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /tmp
      - /var/run
      - /etc/nginx/conf.d

networks:
  myapp-network:
    driver: bridge
